/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RecruitmentPostType = IDL.Variant({
  'result' : IDL.Null,
  'answerKey' : IDL.Null,
  'recruitmentForm' : IDL.Null,
  'admitCard' : IDL.Null,
});
export const KeyValue = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const PostStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const RecruitmentPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'postType' : RecruitmentPostType,
  'title' : IDL.Text,
  'vacancyDetails' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'eligibility' : IDL.Text,
  'updatedAt' : Time,
  'applicationFee' : IDL.Text,
  'officialLinks' : IDL.Vec(KeyValue),
  'importantDates' : IDL.Vec(KeyValue),
  'organization' : IDL.Text,
  'ageLimit' : IDL.Text,
  'examPostName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [
        RecruitmentPostType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(KeyValue),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(KeyValue),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(RecruitmentPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(RecruitmentPost)], ['query']),
  'getPostsByType' : IDL.Func(
      [RecruitmentPostType],
      [IDL.Vec(RecruitmentPost)],
      ['query'],
    ),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(RecruitmentPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishPost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPostsByTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RecruitmentPost)],
      ['query'],
    ),
  'unpublishPost' : IDL.Func([IDL.Nat], [], []),
  'updatePost' : IDL.Func(
      [
        IDL.Nat,
        RecruitmentPostType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(KeyValue),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(KeyValue),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RecruitmentPostType = IDL.Variant({
    'result' : IDL.Null,
    'answerKey' : IDL.Null,
    'recruitmentForm' : IDL.Null,
    'admitCard' : IDL.Null,
  });
  const KeyValue = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const PostStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const RecruitmentPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'postType' : RecruitmentPostType,
    'title' : IDL.Text,
    'vacancyDetails' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'eligibility' : IDL.Text,
    'updatedAt' : Time,
    'applicationFee' : IDL.Text,
    'officialLinks' : IDL.Vec(KeyValue),
    'importantDates' : IDL.Vec(KeyValue),
    'organization' : IDL.Text,
    'ageLimit' : IDL.Text,
    'examPostName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [
          RecruitmentPostType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(KeyValue),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(KeyValue),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(RecruitmentPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(RecruitmentPost)], ['query']),
    'getPostsByType' : IDL.Func(
        [RecruitmentPostType],
        [IDL.Vec(RecruitmentPost)],
        ['query'],
      ),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(RecruitmentPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishPost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPostsByTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RecruitmentPost)],
        ['query'],
      ),
    'unpublishPost' : IDL.Func([IDL.Nat], [], []),
    'updatePost' : IDL.Func(
        [
          IDL.Nat,
          RecruitmentPostType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(KeyValue),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(KeyValue),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };