/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface KeyValue { 'key' : string, 'value' : string }
export type PostStatus = { 'published' : null } |
  { 'draft' : null };
export interface RecruitmentPost {
  'id' : bigint,
  'status' : PostStatus,
  'postType' : RecruitmentPostType,
  'title' : string,
  'vacancyDetails' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'eligibility' : string,
  'updatedAt' : Time,
  'applicationFee' : string,
  'officialLinks' : Array<KeyValue>,
  'importantDates' : Array<KeyValue>,
  'organization' : string,
  'ageLimit' : string,
  'examPostName' : string,
}
export type RecruitmentPostType = { 'result' : null } |
  { 'answerKey' : null } |
  { 'recruitmentForm' : null } |
  { 'admitCard' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<
    [
      RecruitmentPostType,
      string,
      string,
      string,
      Array<KeyValue>,
      string,
      string,
      string,
      string,
      Array<KeyValue>,
      Array<string>,
    ],
    bigint
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllPosts' : ActorMethod<[], Array<RecruitmentPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPostById' : ActorMethod<[bigint], [] | [RecruitmentPost]>,
  'getPostsByType' : ActorMethod<[RecruitmentPostType], Array<RecruitmentPost>>,
  'getPublishedPosts' : ActorMethod<[], Array<RecruitmentPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishPost' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPostsByTag' : ActorMethod<[string], Array<RecruitmentPost>>,
  'unpublishPost' : ActorMethod<[bigint], undefined>,
  'updatePost' : ActorMethod<
    [
      bigint,
      RecruitmentPostType,
      string,
      string,
      string,
      Array<KeyValue>,
      string,
      string,
      string,
      string,
      Array<KeyValue>,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];