/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RecruitmentPost {
    id: bigint;
    status: PostStatus;
    postType: RecruitmentPostType;
    title: string;
    vacancyDetails: string;
    createdAt: Time;
    tags: Array<string>;
    eligibility: string;
    updatedAt: Time;
    applicationFee: string;
    officialLinks: Array<KeyValue>;
    importantDates: Array<KeyValue>;
    organization: string;
    ageLimit: string;
    examPostName: string;
}
export interface KeyValue {
    key: string;
    value: string;
}
export interface UserProfile {
    name: string;
}
export enum PostStatus {
    published = "published",
    draft = "draft"
}
export enum RecruitmentPostType {
    result = "result",
    answerKey = "answerKey",
    recruitmentForm = "recruitmentForm",
    admitCard = "admitCard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(postType: RecruitmentPostType, title: string, organization: string, examPostName: string, importantDates: Array<KeyValue>, eligibility: string, applicationFee: string, ageLimit: string, vacancyDetails: string, officialLinks: Array<KeyValue>, tags: Array<string>): Promise<bigint>;
    deletePost(id: bigint): Promise<void>;
    getAllPosts(): Promise<Array<RecruitmentPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPostById(id: bigint): Promise<RecruitmentPost | null>;
    getPostsByType(postType: RecruitmentPostType): Promise<Array<RecruitmentPost>>;
    getPublishedPosts(): Promise<Array<RecruitmentPost>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishPost(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPostsByTag(tag: string): Promise<Array<RecruitmentPost>>;
    unpublishPost(id: bigint): Promise<void>;
    updatePost(id: bigint, postType: RecruitmentPostType, title: string, organization: string, examPostName: string, importantDates: Array<KeyValue>, eligibility: string, applicationFee: string, ageLimit: string, vacancyDetails: string, officialLinks: Array<KeyValue>, tags: Array<string>): Promise<void>;
}
import type { KeyValue as _KeyValue, PostStatus as _PostStatus, RecruitmentPost as _RecruitmentPost, RecruitmentPostType as _RecruitmentPostType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: RecruitmentPostType, arg1: string, arg2: string, arg3: string, arg4: Array<KeyValue>, arg5: string, arg6: string, arg7: string, arg8: string, arg9: Array<KeyValue>, arg10: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getAllPosts(): Promise<Array<RecruitmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostById(arg0: bigint): Promise<RecruitmentPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByType(arg0: RecruitmentPostType): Promise<Array<RecruitmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByType(to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByType(to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPosts(): Promise<Array<RecruitmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPosts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPosts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishPost(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchPostsByTag(arg0: string): Promise<Array<RecruitmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPostsByTag(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPostsByTag(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishPost(arg0);
            return result;
        }
    }
    async updatePost(arg0: bigint, arg1: RecruitmentPostType, arg2: string, arg3: string, arg4: string, arg5: Array<KeyValue>, arg6: string, arg7: string, arg8: string, arg9: string, arg10: Array<KeyValue>, arg11: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, to_candid_RecruitmentPostType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
}
function from_candid_PostStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RecruitmentPostType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecruitmentPostType): RecruitmentPostType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RecruitmentPost_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecruitmentPost): RecruitmentPost {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecruitmentPost]): RecruitmentPost | null {
    return value.length === 0 ? null : from_candid_RecruitmentPost_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PostStatus;
    postType: _RecruitmentPostType;
    title: string;
    vacancyDetails: string;
    createdAt: _Time;
    tags: Array<string>;
    eligibility: string;
    updatedAt: _Time;
    applicationFee: string;
    officialLinks: Array<_KeyValue>;
    importantDates: Array<_KeyValue>;
    organization: string;
    ageLimit: string;
    examPostName: string;
}): {
    id: bigint;
    status: PostStatus;
    postType: RecruitmentPostType;
    title: string;
    vacancyDetails: string;
    createdAt: Time;
    tags: Array<string>;
    eligibility: string;
    updatedAt: Time;
    applicationFee: string;
    officialLinks: Array<KeyValue>;
    importantDates: Array<KeyValue>;
    organization: string;
    ageLimit: string;
    examPostName: string;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n8(_uploadFile, _downloadFile, value.status),
        postType: from_candid_RecruitmentPostType_n10(_uploadFile, _downloadFile, value.postType),
        title: value.title,
        vacancyDetails: value.vacancyDetails,
        createdAt: value.createdAt,
        tags: value.tags,
        eligibility: value.eligibility,
        updatedAt: value.updatedAt,
        applicationFee: value.applicationFee,
        officialLinks: value.officialLinks,
        importantDates: value.importantDates,
        organization: value.organization,
        ageLimit: value.ageLimit,
        examPostName: value.examPostName
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: null;
} | {
    answerKey: null;
} | {
    recruitmentForm: null;
} | {
    admitCard: null;
}): RecruitmentPostType {
    return "result" in value ? RecruitmentPostType.result : "answerKey" in value ? RecruitmentPostType.answerKey : "recruitmentForm" in value ? RecruitmentPostType.recruitmentForm : "admitCard" in value ? RecruitmentPostType.admitCard : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "draft" in value ? PostStatus.draft : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecruitmentPost>): Array<RecruitmentPost> {
    return value.map((x)=>from_candid_RecruitmentPost_n6(_uploadFile, _downloadFile, x));
}
function to_candid_RecruitmentPostType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecruitmentPostType): _RecruitmentPostType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecruitmentPostType): {
    result: null;
} | {
    answerKey: null;
} | {
    recruitmentForm: null;
} | {
    admitCard: null;
} {
    return value == RecruitmentPostType.result ? {
        result: null
    } : value == RecruitmentPostType.answerKey ? {
        answerKey: null
    } : value == RecruitmentPostType.recruitmentForm ? {
        recruitmentForm: null
    } : value == RecruitmentPostType.admitCard ? {
        admitCard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
